const names = [
  "Liam",
  "Noah",
  "Oliver",
  "Elijah",
  "James",
  "William",
  "Benjamin",
  "Lucas",
  "Henry",
  "Theodore",
  "Jack",
  "Levi",
  "Alexander",
  "Jackson",
  "Mateo",
  "Daniel",
  "Michael",
  "Mason",
  "Sebastian",
  "Ethan",
  "Logan",
  "Owen",
  "Samuel",
  "Jacob",
  "Asher",
  "Aiden",
  "John",
  "Joseph",
  "Wyatt",
  "David",
  "Leo",
  "Luke",
  "Julian",
  "Hudson",
  "Grayson",
  "Matthew",
  "Ezra",
  "Gabriel",
  "Carter",
  "Isaac",
  "Jayden",
  "Luca",
  "Anthony",
  "Dylan",
  "Lincoln",
  "Thomas",
  "Maverick",
  "Elias",
  "Josiah",
  "Charles",
  "Christopher",
  "Ezekiel",
  "Miles",
  "Jaxon",
  "Isaiah",
  "Andrew",
  "Joshua",
  "Nathan",
  "Nolan",
  "Adrian",
  "Cameron",
  "Santiago",
  "Eli",
  "Aaron",
  "Ryan",
  "Angel",
  "Cooper",
  "Waylon",
  "Easton",
  "Kai",
  "Christian",
  "Landon",
  "Colton",
  "Roman",
  "Axel",
  "Brooks",
  "Jonathan",
  "Robert",
  "Jameson",
  "Ian",
  "Everett",
  "Greyson",
  "Wesley",
  "Jeremiah",
  "Hunter",
  "Leonardo",
  "Jordan",
  "José",
  "Bennett",
  "Silas",
  "Nicholas",
  "Parker",
  "Beau",
  "Weston",
  "Austin",
  "Connor",
  "Carson",
  "Dominic",
  "Xavier",
  "Olivia",
  "Emma",
  "Charlotte",
  "Amelia",
  "Ava",
  "Sophia",
  "Isabella",
  "Mia",
  "Evelyn",
  "Harper",
  "Luna",
  "Camila",
  "Gianna",
  "Elizabeth",
  "Eleanor",
  "Ella",
  "Abigail",
  "Sofia",
  "Avery",
  "Scarlett",
  "Emily",
  "Aria",
  "Penelope",
  "Chloe",
  "Layla",
  "Mila",
  "Nora",
  "Hazel",
  "Madison",
  "Ellie",
  "Lily",
  "Nova",
  "Isla",
  "Grace",
  "Violet",
  "Aurora",
  "Riley",
  "Zoey",
  "Willow",
  "Emilia",
  "Stella",
  "Zoe",
  "Victoria",
  "Hannah",
  "Addison",
  "Leah",
  "Lucy",
  "Eliana",
  "Ivy",
  "Everly",
  "Paisley",
  "Elena",
  "Naomi",
  "Maya",
  "Natalie",
  "Kinsley",
  "Delilah",
  "Claire",
  "Audrey",
  "Aaliyah",
  "Ruby",
  "Brooklyn",
  "Alice",
  "Aubrey",
  "Autumn",
  "Leilani",
  "Savannah",
  "Valentina",
  "Kennedy",
  "Madelyn",
  "Josephine",
  "Bella",
  "Skylar",
  "Genesis",
  "Sophie",
  "Hailey",
  "Sadie",
  "Natalia",
  "Quinn",
  "Caroline",
  "Allison",
  "Gabriella",
  "Anna",
  "Serenity",
  "Nevaeh",
  "Cora",
  "Ariana",
  "Emery",
  "Lydia",
  "Jade",
  "Sarah",
  "Eva",
  "Adeline",
  "Madeline",
  "Piper",
  "Rylee",
  "Athena",
  "Peyton",
  "Everleigh",
  "Flynn",
  "Loyal",
  "Everest",
  "Indigo",
  "Caspian",
  "Rome",
  "Hadleigh",
  "Yehuda",
  "India",
  "Guinevere",
  "Fisher",
  "Cordelia",
  "Aislinn",
  "Zechariah",
  "Montgomery",
  "Luz",
  "Zen",
  "Dion",
  "Annalee",
  "Vaughn",
];

const generateButton = document.getElementById("generate-button");
const nameDisplay = document.getElementById("name-display");
const fireworksContainer = document.getElementById("fireworks");

generateButton.addEventListener("click", () => {
  const randomName = names[Math.floor(Math.random() * names.length)];
  nameDisplay.textContent = randomName;
  createFireworks();
});

function createFireworks() {
  const firework = document.createElement("div");
  firework.classList.add("firework");
  firework.style.left = Math.random() * 100 + "vw";
  firework.style.top = Math.random() * 100 + "vh";
  fireworksContainer.appendChild(firework);

  setTimeout(() => {
    firework.remove();
  }, 1000);
}

// Mouse hover animation
document.addEventListener("mousemove", (event) => {
  const sparkle = document.createElement("div");
  sparkle.classList.add("firework");
  sparkle.style.left = event.pageX + "px";
  sparkle.style.top = event.pageY + "px";
  document.body.appendChild(sparkle);

  setTimeout(() => {
    sparkle.remove();
  }, 1000);
});
